/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vcs.changed.text.example;

public class Library {
    public boolean someLibraryMethod() {
      return true;
    }
    /** javadoc content **/
    public boolean anotherLibraryMethod() {
    return true;
    }
//
//    public boolean another(){
//    return false;
//    }
}
